#pragma once
#include "zombies.h"
#include "map.h"

#define SCREENWIDTH 800.0
#define SCREENHEIGHT 600.0
#define BUTTONLENGTHOVERFONT 4.0
#define THEGAMEBELOWTHAT SCREENHEIGHT/6.0
#define STDBUTTONCURVE 0.3
#define BUTTONLINETHICKNESSDIV 500.0
#define BUTTONSHADOWCOLOR (Color){40, 40, 40, 180}
